"""Native non-printing roof enforcers; actual supports are generated by the slicer."""

from dataclasses import dataclass
from typing import Literal

from build123d import Face, GeomType, Location, Part, Solid

from cargo_grid.jobs import Design, Job
from cargo_grid.parameters import Tile, count, positive
from cargo_grid.stacking import Volume
from cargo_grid.tiles import hole_placements

RoofCoverage = Literal["critical", "full"]
CRITICAL_PAD_WIDTH_MM = 3.0
MIN_ENFORCER_HALF_SPAN_MM = 1.0


@dataclass(frozen=True)
class RoofSupportSettings:
    """Intentional PETG-base/PLA-interface contact, not a chemistry guarantee."""

    top_gap: float = 0.0
    interface_layers: int = 2
    interface_spacing: float = 0.0
    nozzle_map: tuple[int, int] | None = None
    coverage: RoofCoverage = "critical"
    foot_expansion: float | None = None

    def __post_init__(self) -> None:
        if self.coverage not in ("critical", "full"):
            raise ValueError("roof coverage must be critical or full")
        positive("roof interface gap", self.top_gap, zero=True)
        count("roof interface layers", self.interface_layers)
        positive("roof interface spacing", self.interface_spacing, zero=True)
        if self.top_gap == 0 and (self.interface_layers < 2 or self.interface_spacing != 0):
            raise ValueError(
                "zero-contact roof support requires at least two dense interface layers with spacing 0"
            )
        if self.foot_expansion is not None and self.foot_expansion != -1:
            positive("roof support-foot expansion", self.foot_expansion, zero=True)
        if self.nozzle_map is not None:
            if len(self.nozzle_map) != 2:
                raise ValueError("roof supports need a PETG/PLA two-nozzle mapping")
            for nozzle in self.nozzle_map:
                count("physical nozzle", nozzle)
            if set(self.nozzle_map) != {1, 2}:
                raise ValueError("PETG and PLA must use distinct physical nozzles 1 and 2")

    @property
    def contact_mode(self) -> Literal["zero-contact", "gapped"]:
        return "zero-contact" if self.top_gap == 0 else "gapped"

    @property
    def process_override_keys(self) -> set[str]:
        keys = set(self.native_settings()) - {"filament_map", "filament_map_mode"}
        if self.contact_mode != "zero-contact":
            keys.discard("support_on_build_plate_only")
        return keys

    def native_settings(self) -> dict[str, str | list[str]]:
        settings: dict[str, str | list[str]] = {
            "enable_support": "1",
            "support_type": "normal(manual)",
            "support_filament": "1",
            "support_interface_filament": "2",
            "support_on_build_plate_only": "0",
            "support_interface_top_layers": str(self.interface_layers),
            "support_top_z_distance": f"{self.top_gap:g}",
            "support_interface_spacing": f"{self.interface_spacing:g}",
        }
        if self.contact_mode == "zero-contact":
            settings["independent_support_layer_height"] = "0"
            settings["support_object_xy_distance"] = "0.4"
        else:
            settings.update(support_expansion="0", support_object_xy_distance="0.35")
        if self.nozzle_map is not None:
            settings.update(
                filament_map=[str(n) for n in self.nozzle_map],
                filament_map_mode="Manual",
            )
        if self.foot_expansion is not None and self.foot_expansion != -1:
            settings["raft_first_layer_expansion"] = f"{self.foot_expansion:g}"
        return settings


def validate_roof_job(job: Job, settings: RoofSupportSettings, layer_height: float) -> None:
    if job.kind not in ("part", "layout"):
        raise ValueError("roof supports require a tile-only part or layout job")
    found_female = False
    for design in job.designs:
        if "family" in design.parameters or "interface" not in design.parameters:
            raise ValueError("roof supports currently require a tile-only part or layout job")
        spec = _tile_spec(design)
        if spec.interface.joint_style != "original":
            raise ValueError("roof supports require original roofed joints, not full-height")
        if (
            settings.top_gap + settings.interface_layers * layer_height
            >= spec.interface.female_opening_height
        ):
            raise ValueError("roof support interface consumes the entire pocket height")
        if layer_height >= spec.interface.height - spec.interface.female_opening_height:
            raise ValueError("layer height is too large for the roof enforcer")
        found_female |= spec.west or spec.south
    if not found_female:
        raise ValueError("this job has no retained west or south female roofs to support")


def _tile_spec(design: Design) -> Tile:
    from cargo_grid.parameters import Interface

    parameters = dict(design.parameters)
    parameters["interface"] = Interface(**parameters["interface"])
    return Tile(**parameters)


def roof_enforcers(
    design: Design, layer_height: float, coverage: RoofCoverage = "critical"
) -> list[Volume]:
    if coverage not in ("critical", "full"):
        raise ValueError("roof coverage must be critical or full")
    spec = _tile_spec(design)
    if not (spec.west or spec.south):
        return []
    ceiling = spec.interface.female_opening_height
    half_span = min(
        max(MIN_ENFORCER_HALF_SPAN_MM, layer_height),
        spec.interface.height - ceiling,
    )
    pitch = spec.interface.pitch
    groups: dict[tuple[Literal["west", "south"], int], list[Face]] = {}
    for face in design.shape.faces():
        bounds = face.bounding_box()
        if not (
            face.geom_type == GeomType.PLANE
            and abs(bounds.min.Z - ceiling) < 1e-5
            and abs(bounds.max.Z - ceiling) < 1e-5
            and face.normal_at().Z < -0.99
        ):
            continue
        side: Literal["west", "south"]
        if spec.west and bounds.min.X >= -1e-5 and bounds.max.X <= 6.1 + 1e-5:
            side, coordinate = "west", face.center().Y
        elif spec.south and bounds.min.Y >= -1e-5 and bounds.max.Y <= 6.0 + 1e-5:
            side, coordinate = "south", face.center().X
        else:
            continue
        index = round(coordinate / pitch - 0.5)
        groups.setdefault((side, index), []).append(face)
    for side, expected in (
        ("west", spec.ny if spec.west else 0),
        ("south", spec.nx if spec.south else 0),
    ):
        found = {index for edge, index in groups if edge == side}
        if found != set(range(expected)):
            raise ValueError(f"{design.name}: expected {expected} planar {side} pocket roofs")
    volumes = []
    cuts = hole_placements(spec)
    edge_cuts = {
        "west": {round(h.y, 6) for h in cuts if h.accepted and abs(h.x) < 1e-6},
        "south": {round(h.x, 6) for h in cuts if h.accepted and abs(h.y) < 1e-6},
    }
    for edge in ("west", "south"):
        for index in sorted(index for side, index in groups if side == edge):
            faces = groups[(edge, index)]
            faces.sort(key=lambda face: (face.center().Y, face.center().X))
            shapes = [
                Part([Solid.extrude(face, (0, 0, 2 * half_span))]).moved(
                    Location((0, 0, -half_span))
                )
                for face in faces
            ]
            # A tangent round cut can split one south roof into two faces.
            # Keep full masks separate to avoid a nonmanifold shared edge.
            masks = [
                ("full" if len(shapes) == 1 else f"full_{n + 1}", shape)
                for n, shape in enumerate(shapes)
            ]
            if coverage == "critical":
                center = (index + 0.5) * pitch
                radius = spec.hole_diameter / 2 if round(center, 6) in edge_cuts[edge] else 0
                offset = max(6.0, radius + 1.0)
                bounds = Part(
                    [solid for shape in shapes for solid in shape.solids()]
                ).bounding_box()
                masks = []
                for band, low in (
                    ("lower", center - offset - CRITICAL_PAD_WIDTH_MM),
                    ("upper", center + offset),
                ):
                    if edge == "west":
                        size = (bounds.size.X + 2, CRITICAL_PAD_WIDTH_MM, bounds.size.Z + 2)
                        origin = (bounds.min.X - 1, low, bounds.min.Z - 1)
                    else:
                        size = (CRITICAL_PAD_WIDTH_MM, bounds.size.Y + 2, bounds.size.Z + 2)
                        origin = (low, bounds.min.Y - 1, bounds.min.Z - 1)
                    clip = Solid.make_box(*size).moved(Location(origin))
                    solids = []
                    for shape in shapes:
                        clipped = shape.intersect(clip)
                        if clipped is not None:
                            solids.extend(clipped.solids())
                    if not solids:
                        raise ValueError(
                            f"{design.name}: critical {edge} roof pad does not fit; select full roof coverage"
                        )
                    masks.append((band, Part(solids)))
            for band, mask in masks:
                if not mask.is_valid or len(mask.solids()) != 1 or mask.volume <= 0:
                    raise ValueError(f"{design.name}: invalid {edge} roof enforcer")
                volumes.append(
                    Volume(
                        f"{design.name}_{edge}_roof_{index + 1}_{coverage}_{band}_enforcer",
                        mask,
                        "roof-enforcer",
                        1,
                        subtype="support_enforcer",
                        roof_side=edge,
                        roof_index=index + 1,
                    )
                )
    return volumes
